// packages/solid/src/app.tsx
import { useContext, createContext } from 'solid-js';
import { RenderApp, injectLibraries, type AppProps, type Libraries } from '@brick/core';

import { useState, useStyles } from './hooks';

injectLibraries({
  useState,
  useStyles,
  useContext,
  createContext: createContext as unknown as Libraries['createContext'],
});

export function App(props: AppProps) {
  return <RenderApp {...props} />;
}

// packages/react/src/app.tsx
import { createContext, useContext, useState } from 'react';

import { type AppProps, injectLibraries, type Libraries, RenderApp } from '@brick/core';

injectLibraries({
  useState,
  useContext: useContext as unknown as Libraries['useContext'],
  createContext: createContext as unknown as Libraries['createContext'],
});

export function App(props: AppProps) {
  return <RenderApp {...props} />;
}
